version: '2'
services:
  proxy:
    build: .
    image: jamorin/nzb-gateway
    environment:
    - SECURITY_OAUTH2_CLIENT_ID=$SECURITY_OAUTH2_CLIENT_ID
    - SECURITY_OAUTH2_CLIENT_SECRET=$SECURITY_OAUTH2_CLIENT_SECRET
    - SECURITY_USER_PASSWORD=password
    ports:
    - "8080:8080"
