spring:
  application:
    name: nzbgateway
  mvc:
    favicon:
      enabled: false
  cloud:
    gateway:
      routes:
      - id: nzbget
        uri: '${gateway.base-url}:6789'
        predicates:
        - Path=/nzbget/**
      - id: nzbget-xmlrpc
        uri: '${gateway.base-url}:6789'
        predicates:
        - Path=/xmlrpc
      - id: sonarr
        uri: '${gateway.base-url}:8989'
        predicates:
        - Path=/sonarr/**
      - id: radarr
        uri: '${gateway.base-url}:7878'
        predicates:
        - Path=/radarr/**
      - id: plexpy
        uri: '${gateway.base-url}:8181'
        predicates:
        - Path=/plexpy/**
  security:
    user:
      name: user
gateway:
  use-forwarded-filter: false
  base-url: http://192.168.86.2
  auth0-roles-namespace: https://nzbgateway/roles


security:
  oauth2:
    client:
      client-id: ${SECURITY_OAUTH2_CLIENT_ID:acme}
      client-secret: ${SECURITY_OAUTH2_CLIENT_SECRET}
      access-token-uri: https://jeremyamorin.auth0.com/oauth/token
      user-authorization-uri: https://jeremyamorin.auth0.com/authorize
      scope:
      - email
    resource:
      user-info-uri: https://jeremyamorin.auth0.com/userinfo
logging:
  file: target/application.log
#  level:
#    org.springframework.cloud.gateway: DEBUG
server:
  servlet:
    session:
      timeout: 120m

